version: '2'
services:
  redis:
      image: "redis:latest"
      container_name: redis
      restart: unless-stopped
      ports:
        - "6379:6379"
      volumes:
       - "./redis.conf:/etc/redis.conf"
      command: "redis-server /etc/redis.conf"

